# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: workhome
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: reto-aws-nodejs20-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-aws-nodejs20-http-api

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
