# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: workhome
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: reto-aws-nodejs20-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-aws-nodejs20-http-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:311141537249:table/RetoTecnicoTable

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getFusionados:
    handler: src/fusionados.fusionados
    events:
      - httpApi:
          path: /fusionados
          method: get
  postAlmacenar:
    handler: src/almacenar.almacenar
    events:
      - httpApi:
          path: /almacenar
          method: post
  getHistorial:
    handler: src/historial.historial
    events:
      - httpApi:
          path: /historial
          method: get

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RetoTecnicoTable
        AttributeDefinitions:
          - AttributeName: characterName
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: characterName
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5