# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: workhome
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: reto-aws-nodejs20-http-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: reto-aws-nodejs20-http-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128 # Es el valor mínimo y el máxomo es 10 GB
  timeout: 5
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:311141537249:table/AlmacenarTable
        - arn:aws:dynamodb:us-east-1:311141537249:table/FusionadosTable
        - arn:aws:dynamodb:us-east-1:311141537249:table/TempCharactersTable
        - arn:aws:dynamodb:us-east-1:311141537249:table/TempPlanetsTable

functions:
  hello:
    handler: handler.hello
    events:
      - http: 
          path: /
          method: get
  getFusionados:
    handler: src/fusionados.fusionados
    events:
      - http:
          path: /fusionados
          method: get
  postAlmacenar:
    handler: src/almacenar.almacenar
    events:
      - http:
          path: /almacenar
          method: post
  getHistorial:
    timeout: 10
    handler: src/historial.historial
    events:
      - http:
          path: /historial
          method: get

resources:
  Resources:
    # First DynamoDB Table
    FirstTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FusionadosTable
        AttributeDefinitions:
          - AttributeName: characterName
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: characterName
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        #TimeToLiveSpecification:
        #    AttributeName: timeToLive
        #    Enabled: true
    # Second DynamoDB Table
    SecondTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AlmacenarTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType:  HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    # Tercera DynamoDB Table
    ThirdTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TempPlanetsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          #- AttributeName: ttlAttribute
          #  AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          #- AttributeName: ttlAttribute
          #  KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttlAttribute
    # Fourth DynamoDB Table
    FourthTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TempCharactersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          #- AttributeName: ttlAttribute
          #  AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          #- AttributeName: ttlAttribute
          #  KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttlAttribute
